//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 3.4
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// $ANTLR 3.4 /home/juanse/Proyectos/webidl-dotnet/WebIDL.g 2012-03-10 17:38:12

// The variable 'variable' is assigned but its value is never used.
#pragma warning disable 219
// Unreachable code detected.
#pragma warning disable 162
// Missing XML comment for publicly visible type or member 'Type_or_Member'
#pragma warning disable 1591
// CLS compliance checking will not be performed on 'type' because it is not visible from outside this assembly.
#pragma warning disable 3019


using System.Collections.Generic;
using Antlr.Runtime;
using Antlr.Runtime.Misc;

namespace  WebIDL.Grammar 
{
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "3.4")]
[System.CLSCompliant(false)]
public partial class WebIDLLexer : Antlr.Runtime.Lexer
{
	public const int EOF=-1;
	public const int WS=4;

    // delegates
    // delegators

	public WebIDLLexer()
	{
		OnCreated();
	}

	public WebIDLLexer(ICharStream input )
		: this(input, new RecognizerSharedState())
	{
	}

	public WebIDLLexer(ICharStream input, RecognizerSharedState state)
		: base(input, state)
	{

		OnCreated();
	}
	public override string GrammarFileName { get { return "/home/juanse/Proyectos/webidl-dotnet/WebIDL.g"; } }


	partial void OnCreated();
	partial void EnterRule(string ruleName, int ruleIndex);
	partial void LeaveRule(string ruleName, int ruleIndex);

	partial void EnterRule_WS();
	partial void LeaveRule_WS();

	// $ANTLR start "WS"
	[GrammarRule("WS")]
	private void mWS()
	{
		EnterRule_WS();
		EnterRule("WS", 1);
		TraceIn("WS", 1);
		try
		{
			int _type = WS;
			int _channel = DefaultTokenChannel;
			// /home/juanse/Proyectos/webidl-dotnet/WebIDL.g:15:4: ( ' ' )
			DebugEnterAlt(1);
			// /home/juanse/Proyectos/webidl-dotnet/WebIDL.g:15:6: ' '
			{
			DebugLocation(15, 6);
			Match(' '); 
			DebugLocation(15, 10);
			_channel=HIDDEN;

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("WS", 1);
			LeaveRule("WS", 1);
			LeaveRule_WS();
		}
	}
	// $ANTLR end "WS"

	public override void mTokens()
	{
		// /home/juanse/Proyectos/webidl-dotnet/WebIDL.g:1:8: ( WS )
		DebugEnterAlt(1);
		// /home/juanse/Proyectos/webidl-dotnet/WebIDL.g:1:10: WS
		{
		DebugLocation(1, 10);
		mWS(); 

		}


	}


	#region DFA

	protected override void InitDFAs()
	{
		base.InitDFAs();
	}

 
	#endregion

}

} // namespace  WebIDL.Grammar 
